port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894

unified-delay: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: false
mode: rule
log-level: info
ipv6: true
udp: true

external-controller: 127.0.0.1:9090
# external-ui: ui
# external-ui-url: 'https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'

geox-url:
  # geoip: 'https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat'
  # geosite: 'https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat'
  mmdb: 'https://geodata.kelee.one/Country-Masaiki.mmdb'
  asn: 'https://geodata.kelee.one/GeoLite2-ASN-P3TERX.mmdb'

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com

  skip-domain:
    - Mijia Cloud

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

# P2Pä¸‹è½½ç«¯å£
# listeners:
# - name: socks5-in-1
#   type: socks
#   port: 10808
#   listen: 0.0.0.0
#   udp: true
#   users: []
#   proxy: DIRECT

dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - +.lan
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query

# é”šç‚¹ - èŠ‚ç‚¹è®¢é˜…çš„å‚æ•° [æ¯å°æ—¶æ›´æ–°ä¸€æ¬¡è®¢é˜…èŠ‚ç‚¹ï¼Œæ¯ 6 ç§’ä¸€æ¬¡å¥åº·æ£€æŸ¥]
NodeParam: &NodeParam {type: http, interval: 3600, health-check: {enable: true, url: 'http://www.google.com/blank.html', interval: 6}}

# é”šç‚¹ - èŠ‚ç‚¹è®¢é˜…
proxy-providers: 
  TODO-name:
    url: 'TODO-providerUrl'
    <<: *NodeParam
    path: './proxy_providers/TODO-provider.yaml'
    override:
      additional-prefix: "[TODO-prefix]" # ä¸ºè®¢é˜…èŠ‚ç‚¹æ·»åŠ æœºåœºåç§°å‰ç¼€

proxies:
- name: "wg"
  type: wireguard
  ip: TODO
  private-key: TODO
  peers:
    - server: TODO
      port: TODO
      public-key: TODO
      pre-shared-key: TODO
      allowed-ips: ['0.0.0.0/0']     # åˆ†æµç”±clashå¤„ç†
      # reserved: [209,98,59]        # å¦‚æœéœ€è¦è‡ªå·±å¡«
  udp: true

# é”šç‚¹ - èŠ‚ç‚¹ç­›é€‰ç»„
FilterHK: &FilterHK '^(?=.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|Hong)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterTW: &FilterTW '^(?=.*((?i)ğŸ‡¹ğŸ‡¼|å°æ¹¾|(\b(TW|Tai|Taiwan)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterJP: &FilterJP '^(?=.*((?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|Japan)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterKR: &FilterKR '^(?=.*((?i)ğŸ‡°ğŸ‡·|éŸ©å›½|éŸ“|é¦–å°”|(\b(KR|Korea)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterSG: &FilterSG '^(?=.*((?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|Singapore)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterUS: &FilterUS '^(?=.*((?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|United States)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterUK: &FilterUK '^(?=.*((?i)ğŸ‡¬ğŸ‡§|è‹±å›½|ä¼¦æ•¦|(\b(UK|United Kingdom)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterFR: &FilterFR '^(?=.*((?i)ğŸ‡«ğŸ‡·|æ³•å›½|(\b(FR|France)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterDE: &FilterDE '^(?=.*((?i)ğŸ‡©ğŸ‡ª|å¾·å›½|(\b(DE|Germany)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$'
FilterGame: &FilterGame '^(?=.*((?i)æ¸¸æˆ|ğŸ®|(\b(GAME)(\d+)?\b)))(?!.*((?i)å›å›½|æ ¡å›­)).*$'
FilterAll: &FilterAll '^(?=.*(.))(?!.*((?i)ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|(\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author)(\d+)?\b|(\d{4}-\d{2}-\d{2}|\dG)))).*$'

# ç­–ç•¥ç»„å‚æ•°é”šç‚¹
# é”šç‚¹ - æ—¶å»¶ä¼˜é€‰å‚æ•° [æ¯ 6 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œå®¹å·® 20msï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
UrlTest: &UrlTest {type: url-test, interval: 6, tolerance: 20, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}
# é”šç‚¹ - æ•…éšœè½¬ç§»å‚æ•° [æ¯ 6 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
FallBack: &FallBack {type: fallback, interval: 6, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}
# é”šç‚¹ - è´Ÿè½½å‡è¡¡å‚æ•° [æ¯ 6 ç§’ä¸€æ¬¡æƒ°æ€§å¥åº·æ£€æŸ¥ï¼Œæ—¶å»¶è¶…è¿‡ 2 ç§’åˆ¤å®šä¸ºå¤±è´¥ï¼Œå¤±è´¥ 3 æ¬¡åˆ™è‡ªåŠ¨è§¦å‘å¥åº·æ£€æŸ¥]
LoadBalance: &LoadBalance {type: load-balance, interval: 6, lazy: true, url: 'http://www.google.com/blank.html', disable-udp: false, strategy: consistent-hashing, timeout: 2000, max-failed-times: 3, hidden: true, include-all-providers: true}
# é”šç‚¹ - è§„åˆ™å‚æ•° [æ¯å°æ—¶æ›´æ–°ä¸€æ¬¡è®¢é˜…è§„åˆ™ï¼Œæ›´æ–°è§„åˆ™æ—¶ä½¿ç”¨ç›´è¿ç­–ç•¥]
YamlRuleProviders: &YamlRuleProviders {type: http, behavior: classical, interval: 3600, format: yaml, proxy: å…œåº•ç­–ç•¥}
TextRuleProviders: &TextRuleProviders {type: http, behavior: classical, interval: 3600, format: text, proxy: å…œåº•ç­–ç•¥}

# ç­–ç•¥ç»„
proxy-groups: 
  - {name: AI, type: select, include-all-providers: true, filter: *FilterAll, proxies: [ç¾å›½è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥]}
  - {name: Youtube, type: select, proxies: [é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: AppleTV, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  # - {name: Netflix, type: select, proxies: [é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: å›½å¤–åª’ä½“, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: å¢ƒå¤–ä¸‹è½½, type: select, include-all-providers: true, filter: *FilterAll, proxies: [DIRECT]}
  - {name: Telegram, type: select, proxies: [é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: æ¸¸æˆé€‰æ‹©, type: select, include-all-providers: true, filter: *FilterGame, proxies: [DIRECT]}
  - {name: App Store, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: Appleè´¦æˆ·, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: TestFlight, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: 1Password, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  # - {name: Microsoft, type: select, proxies: [DIRECT, é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}
  - {name: å…œåº•åå¤‡ç­–ç•¥, type: fallback, proxies: [é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, å°æ¹¾è‡ªåŠ¨ç­–ç•¥, æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, éŸ©å›½è‡ªåŠ¨ç­–ç•¥, æ–°å›½è‡ªåŠ¨ç­–ç•¥, ç¾å›½è‡ªåŠ¨ç­–ç•¥, è‹±å›½è‡ªåŠ¨ç­–ç•¥, æ³•å›½è‡ªåŠ¨ç­–ç•¥, å¾·å›½è‡ªåŠ¨ç­–ç•¥]}

  - {name: é¦™æ¸¯è‡ªåŠ¨ç­–ç•¥, type: select, proxies: [â±é¦™æ¸¯æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥é¦™æ¸¯æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›é¦™æ¸¯è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: å°æ¹¾è‡ªåŠ¨ç­–ç•¥, type: select, proxies: [â±å°æ¹¾æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥å°æ¹¾æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›å°æ¹¾è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: æ—¥æœ¬è‡ªåŠ¨ç­–ç•¥, type: select, proxies: [â±æ—¥æœ¬æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥æ—¥æœ¬æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›æ—¥æœ¬è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: éŸ©å›½è‡ªåŠ¨ç­–ç•¥, type: select, proxies: [â±éŸ©å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥éŸ©å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›éŸ©å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: æ–°å›½è‡ªåŠ¨ç­–ç•¥, type: select, proxies: [â±æ–°å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥æ–°å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›æ–°å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: ç¾å›½è‡ªåŠ¨ç­–ç•¥, type: select, proxies: [â±ç¾å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥ç¾å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›ç¾å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: è‹±å›½è‡ªåŠ¨ç­–ç•¥, type: select, proxies: [â±è‹±å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥è‹±å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›è‹±å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: æ³•å›½è‡ªåŠ¨ç­–ç•¥, type: select, proxies: [â±æ³•å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥æ³•å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›æ³•å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}
  - {name: å¾·å›½è‡ªåŠ¨ç­–ç•¥, type: select, proxies: [â±å¾·å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, ğŸš¥å¾·å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, ğŸ›å¾·å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„]}

# æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„
  - {name: â±é¦™æ¸¯æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterHK}
  - {name: â±å°æ¹¾æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterTW}
  - {name: â±æ—¥æœ¬æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterJP}
  - {name: â±éŸ©å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterKR}
  - {name: â±æ–°å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterSG}
  - {name: â±ç¾å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterUS}
  - {name: â±è‹±å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterUK}
  - {name: â±æ³•å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterFR}
  - {name: â±å¾·å›½æ—¶å»¶ä¼˜é€‰ç­–ç•¥ç»„, <<: *UrlTest, filter: *FilterDE}

# æ•…éšœè½¬ç§»ç­–ç•¥ç»„
  - {name: ğŸš¥é¦™æ¸¯æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterHK}
  - {name: ğŸš¥å°æ¹¾æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterTW}
  - {name: ğŸš¥æ—¥æœ¬æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterJP}
  - {name: ğŸš¥éŸ©å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterKR}
  - {name: ğŸš¥æ–°å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterSG}
  - {name: ğŸš¥ç¾å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterUS}
  - {name: ğŸš¥è‹±å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterUK}
  - {name: ğŸš¥æ³•å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterFR}
  - {name: ğŸš¥å¾·å›½æ•…éšœè½¬ç§»ç­–ç•¥ç»„, <<: *FallBack, filter: *FilterDE}

# è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„
  - {name: ğŸ›é¦™æ¸¯è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterHK}
  - {name: ğŸ›å°æ¹¾è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterTW}
  - {name: ğŸ›æ—¥æœ¬è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterJP}
  - {name: ğŸ›éŸ©å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterKR}
  - {name: ğŸ›æ–°å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterSG}
  - {name: ğŸ›ç¾å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterUS}
  - {name: ğŸ›è‹±å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterUK}
  - {name: ğŸ›æ³•å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterFR}
  - {name: ğŸ›å¾·å›½è´Ÿè½½å‡è¡¡ç­–ç•¥ç»„, <<: *LoadBalance, filter: *FilterDE}

# è®¢é˜…è§„åˆ™
rule-providers:
  LAN:
    <<: *YamlRuleProviders
    path: './rules/Lan.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/LAN_SPLITTER.yaml'

  CustomDirect:
    <<: *TextRuleProviders
    path: './rules/Direct.list'
    url: 'https://raw.githubusercontent.com/Pollo3470/rules/refs/heads/main/Ruleset/Direct.list'

  Direct:
    <<: *YamlRuleProviders
    path: './rules/Direct.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Direct.yaml'

  Proxy:
    <<: *YamlRuleProviders
    path: './rules/Proxy.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Proxy.yaml'

  ChinaDownloadCDN:
    <<: *YamlRuleProviders
    path: './rules/ChinaDownloadCDN.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/ChinaDownloadCDN.yaml'

  InternationalDownloadCDN:
    <<: *YamlRuleProviders
    path: './rules/InternationalDownloadCDN.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/InternationalDownloadCDN.yaml'

  CustomAI:
    <<: *TextRuleProviders
    path: './rules/AI.list'
    url: 'https://raw.githubusercontent.com/Pollo3470/rules/refs/heads/main/Ruleset/AI.list'

  AI:
    <<: *YamlRuleProviders
    path: './rules/AI.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/AI.yaml'

  Game:
    <<: *YamlRuleProviders
    path: './rules/Game.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Game.yaml'

  1Password:
    <<: *YamlRuleProviders
    path: './rules/1PasswordUS.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/1PasswordUS.yaml'

  Steam:
    <<: *YamlRuleProviders
    path: './rules/Steam.yaml'
    url: 'https://rule.kelee.one/Clash/Steam.yaml'

  # Netflix:
  #   <<: *YamlRuleProviders
  #   path: './rules/Netflix.yaml'
  #   url: 'https://rule.kelee.one/Clash/Netflix.yaml'

  Youtube:
    <<: *TextRuleProviders
    path: './rules/Youtube.list'
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list'

  AppleTV:
    <<: *TextRuleProviders
    path: './rules/AppleTV.list'
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleTV.list'

  ProxyMedia:
    <<: *TextRuleProviders
    path: './rules/ProxyMedia.list'
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list'

  iCloudChina:
    <<: *YamlRuleProviders
    path: './rules/iCloudChina.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/iCloudChina.yaml'

  ApplePushNotificationService:
    <<: *YamlRuleProviders
    path: './rules/ApplePushNotificationService.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/ApplePushNotificationService.yaml'

  AppleSoftwareUpdates:
    <<: *YamlRuleProviders
    path: './rules/AppleSoftwareUpdates.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/AppleSoftwareUpdates.yaml'

  AppleID:
    <<: *YamlRuleProviders
    path: './rules/AppleID.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/AppleID.yaml'

  AppStore:
    <<: *YamlRuleProviders
    path: './rules/AppStore.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/AppStore.yaml'

  TestFlight:
    <<: *YamlRuleProviders
    path: './rules/TestFlight.yaml'
    url: 'https://rule.kelee.one/Clash/TestFlight.yaml'

  Microsoft:
    <<: *YamlRuleProviders
    path: './rules/Microsoft.yaml'
    url: 'https://rule.kelee.one/Clash/Microsoft.yaml'

  Google:
    <<: *YamlRuleProviders
    path: './rules/Google.yaml'
    url: 'https://rule.kelee.one/Clash/Google.yaml'

  Telegram:
    <<: *YamlRuleProviders
    path: './rules/Telegram.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/Telegram.yaml'

  ESET_China:
    <<: *YamlRuleProviders
    path: './rules/ESET_China.yaml'
    url: 'https://kelee.one/Tool/Clash/Rule/ESET_China.yaml'

# è§„åˆ™æŒ‡å‘
rules:
  - AND,((NOT,((IP-CIDR,192.168.5.198/32))),(DST-PORT, 0-25564),(IP-CIDR,192.168.5.0/24,no-resolve)), wg
  - RULE-SET, LAN, DIRECT
  - RULE-SET, CustomDirect, DIRECT
  - RULE-SET, Direct, DIRECT
  - RULE-SET, CustomAI, AI
  - RULE-SET, AI, AI
  - RULE-SET, Steam, å…œåº•åå¤‡ç­–ç•¥
  - RULE-SET, Game, æ¸¸æˆé€‰æ‹©
  # - RULE-SET, Netflix, Netflix
  - RULE-SET, Youtube, Youtube
  - RULE-SET, AppleTV, AppleTV
  - RULE-SET, ProxyMedia, å›½å¤–åª’ä½“
  - RULE-SET, TestFlight, TestFlight
  - RULE-SET, iCloudChina, DIRECT
  - RULE-SET, ApplePushNotificationService, DIRECT
  - RULE-SET, AppleSoftwareUpdates, DIRECT
  - RULE-SET, AppleID, Appleè´¦æˆ·
  - RULE-SET, AppStore, App Store
  - RULE-SET, 1Password, 1Password
  - RULE-SET, Microsoft, å…œåº•åå¤‡ç­–ç•¥
  - RULE-SET, Google, å…œåº•åå¤‡ç­–ç•¥
  - RULE-SET, Telegram, Telegram
  - RULE-SET, Proxy, å…œåº•åå¤‡ç­–ç•¥
  - RULE-SET, ChinaDownloadCDN, DIRECT
  - RULE-SET, InternationalDownloadCDN, å¢ƒå¤–ä¸‹è½½
  - RULE-SET, ESET_China, DIRECT
  - GEOIP, CN, DIRECT
  - MATCH, å…œåº•åå¤‡ç­–ç•¥
